# Generated by Django 2.2 on 2019-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
